import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/ui/sidebar/Sidebar";

const inter = Poppins({ subsets: ['latin'] , weight: '400' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex justify-between items-start`}>
        <Sidebar />
        <main className="w-full h-full">
          {children}
        </main>
      </body>
    </html>
  );
}
